name: team approval workflow
on: pull_request_review

jobs:
  labelWhenApproved:
    runs-on: ubuntu-latest
    steps:
      - name: label-approved-action
        uses: AnandChowdhary/label-approved-action@v1.0.00
        env:
          APPROVALS: "1"
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          ADD_LABEL: "approved"
